Fixed possible NPE in popup menu on CanvasJvm
java.lang.NullPointerException: Cannot invoke "java.awt.Point.getX()" because the return value of "ch.scorpion.jabbah.draw.view.CanvasJvm.getMousePosition()" is null
	at ch.scorpion.jabbah.draw.view.CanvasJvm$1.popupMenuWillBecomeVisible(CanvasJvm.kt:74)
	at java.desktop/javax.swing.JPopupMenu.firePopupMenuWillBecomeVisible(JPopupMenu.java:696)